
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

/* %not-for-header */

/* %if-c-only */
/* %if-not-reentrant */

/* %endif */
/* %endif */
/* %ok-for-header */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* %if-c++-only */
/* %endif */

/* %if-c-only */
    
/* %endif */

/* %if-c-only */

/* %endif */

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
/* %if-c-only */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>
/* %endif */

/* %if-tables-serialization */
/* %endif */
/* end standard C headers. */

/* %if-c-or-c++ */
/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* %endif */

/* %if-c++-only */
/* %endif */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* %not-for-header */

/* Returned upon end-of-file. */
#define YY_NULL 0
/* %ok-for-header */

/* %not-for-header */

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)
/* %ok-for-header */

/* %if-reentrant */
/* %endif */

/* %if-not-reentrant */

/* %endif */

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

/* %if-not-reentrant */
extern int yyleng;
/* %endif */

/* %if-c-only */
/* %if-not-reentrant */
extern FILE *yyin, *yyout;
/* %endif */
/* %endif */

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
/* %if-c-only */
	FILE *yy_input_file;
/* %endif */

/* %if-c++-only */
/* %endif */

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* %if-c-only Standard (non-C++) definition */
/* %not-for-header */

/* %if-not-reentrant */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */
/* %endif */
/* %ok-for-header */

/* %endif */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* %if-c-only Standard (non-C++) definition */

/* %if-not-reentrant */
/* %not-for-header */

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;
/* %ok-for-header */

/* %endif */

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,int len  );

/* %endif */

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* %% [1.0] yytext/yyin/yyout/yy_state_type/yylineno etc. def's & init go here */
/* Begin user sect3 */

#define FLEX_DEBUG

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

/* %if-c-only Standard (non-C++) definition */

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* %endif */

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
/* %% [2.0] code to fiddle yytext and yyleng for yymore() goes here \ */\
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
/* %% [3.0] code to copy yytext_ptr to yytext[] goes here, if %array \ */\
	(yy_c_buf_p) = yy_cp;

/* %% [4.0] data tables for the DFA and the user's section 1 definitions go here */
#define YY_NUM_RULES 105
#define YY_END_OF_BUFFER 106
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[480] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,  106,  104,
        8,    6,  104,    7,  103,  104,  103,  104,  104,  103,
      103,  103,  103,   99,    9,  103,  103,  103,  102,  102,
      102,  102,  102,  102,  102,  102,  102,  102,  102,  102,
      102,  101,  101,  101,  101,  101,  101,  101,  101,  101,
      101,  101,  101,  101,  101,  101,  101,  104,    8,    5,
      104,    7,  104,  101,    2,    3,  101,  101,  105,    0,
        9,    7,   45,    0,   97,   51,    0,   48,   55,   54,
        0,    1,    0,   99,   33,    9,   47,   42,   44,   43,
       46,  100,  100,  100,  100,  100,  100,  100,  100,  100,

      100,  100,  100,  100,  100,  100,  100,  100,  100,  100,
      100,  100,  100,  101,  101,  101,  101,  101,  101,  101,
       63,  101,  101,  101,  101,   66,   68,  101,  101,  101,
      101,   74,   50,  101,  101,  101,  101,  101,  101,  101,
       70,  101,  101,   49,    0,    2,    3,    7,    0,    4,
       12,    2,  101,  101,   96,   53,    1,   98,  100,  100,
      100,  100,  100,  100,  100,  100,  100,  100,  100,  100,
      100,  100,  100,  100,  100,  100,  100,  100,  100,  100,
      100,  100,  100,  100,   52,  101,  101,  101,  101,  101,
      101,  101,  101,  101,   65,  101,  101,  101,  101,  101,

      101,  101,  101,  101,  101,  101,  101,  101,  101,  101,
      101,    0,  101,  101,  101,   11,  100,  100,  100,  100,
      100,  100,  100,  100,  100,  100,  100,  100,  100,  100,
       32,  100,  100,  100,   26,  100,  100,  100,    0,   94,
       15,  100,  101,   60,  101,  101,   93,  101,  101,  101,
      101,   67,  101,  101,   69,  101,   39,  101,   56,  101,
       58,  101,  101,  101,  101,  101,  101,  101,  101,  101,
       71,    0,    0,  101,  101,  101,  100,  100,   31,  100,
      100,  100,  100,  100,   28,   95,  100,   29,  100,  100,
      100,  100,   30,  100,  100,   92,    0,   14,  101,  101,

      101,  101,  101,  101,  101,  101,  101,   78,    0,   76,
      101,  101,  101,  101,  101,   77,  101,  101,  101,  101,
        0,    0,  101,   64,  101,  100,  100,  100,  100,  100,
       17,  100,  100,  100,  100,  100,  100,   61,  100,    0,
      101,   40,  101,  101,  101,  101,  101,  101,   38,    0,
      101,  101,  101,  101,  101,  101,  101,  101,  101,    0,
        0,  101,  101,  100,  100,   27,  100,   20,  100,  100,
      100,   24,  100,   13,   23,    0,   90,  101,  101,   86,
        0,   79,   72,    0,  101,  101,   82,   84,  101,  101,
      101,  101,    0,    0,    0,  101,   10,   62,  100,  100,

      100,   16,  100,  100,    0,   91,  101,    0,    0,  101,
      101,  101,  101,  101,   73,    0,    0,    0,  101,   22,
       25,  100,  100,   21,    0,   35,    0,    0,   57,   59,
      101,    0,  101,    0,    0,    0,   81,  100,   19,    0,
       34,    0,    0,   88,    0,   83,    0,    0,    0,   18,
        0,    0,    0,   85,    0,    0,    0,    0,    0,    0,
        0,    0,    0,   80,    0,    0,    0,   75,    0,    0,
       41,    0,   87,   89,    0,    0,   37,   36,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        4,    4,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    5,    6,    7,    1,    1,    8,    9,   10,    8,
        8,   11,   12,    8,   13,   14,   15,   16,   16,   16,
       16,   16,   16,   16,   16,   16,   16,   17,    8,   18,
       19,   20,    1,    1,   21,   22,   23,   24,   25,   26,
       27,   27,   28,   27,   27,   29,   27,   27,   27,   30,
       27,   31,   32,   33,   34,   27,   27,   27,   27,   27,
        8,   35,    8,    1,   36,    1,   37,   38,   39,   40,

       41,   42,   43,   44,   45,   46,   47,   48,   49,   50,
       51,   52,   53,   54,   55,   56,   57,   58,   59,   60,
       61,   62,   63,   64,   65,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[66] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    3,    1,    1,    1,    1,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    1,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    1,    1,    1
    } ;

static yyconst flex_int16_t yy_base[486] =
    {   0,
        0,    0,   64,   68,   72,   76,    0,    0,  618,  619,
       80,   85,   89,  140,  598,  609,  619,  606,    0,   85,
      595,  599,  597,   84,  116,   91,  592,   95,   84,  559,
       81,  568,   78,   91,    0,  558,  562,   97,   99,   95,
      118,  103,    0,  552,  105,  557,  108,   74,  109,  126,
      122,  567,  128,  127,  552,  552,  557,  536,  175,  183,
      191,  199,  204,  155,  215,  619,  122,  558,  619,  219,
      223,  227,  619,  591,  590,  619,  586,  619,  619,  619,
      581,    0,  578,  175,  619,  247,  619,  619,  619,  619,
      619,    0,  537,  191,  541,  554,  541,  547,  530,  536,

      557,  535,  197,  529,  529,  531,  531,  160,  543,  541,
      544,  522,  524,    0,  535,  535,  530,  531,  516,   37,
      513,  519,  513,  513,  515,    0,  525,  514,  524,  502,
      511,    0,  520,  127,  509,  187,  505,  507,  515,  517,
        0,  220,  509,  619,  255,  263,  619,  271,  275,  619,
        0,  279,  512,  493,  619,  619,    0,  535,  505,  492,
      511,  499,  492,  493,  499,  498,  503,  509,  501,  498,
      482,  496,  480,  479,  491,  490,  484,  490,  473,  490,
      515,  502,  479,  477,    0,  483,  504,  485,  482,  157,
      475,  481,  481,  476,  206,  467,  474,  467,  476,  244,

      260,  471,  471,  454,  466,  471,  459,  449,  462,  452,
      490,  450,  447,  452,  460,    0,  440,  448,  435,  454,
      457,  436,  442,  437,  446,  464,  432,  427,  441,  442,
        0,  439,  429,  441,    0,  444,  432,  438,  426,    0,
        0,  436,  426,  619,  419,  433,  457,  422,  431,  422,
      420,    0,  431,  430,    0,  406,  452,  416,  619,  413,
      619,  412,  407,  415,  414,  417,  401,  411,  414,  406,
        0,  401,  415,  411,  409,  392,  411,  406,    0,  409,
      406,  388,  402,  391,    0,    0,  396,    0,  403,  398,
      382,  400,    0,  380,  379,    0,  397,    0,  393,  391,

      381,  375,  388,  387,  382,  387,  369,    0,  373,    0,
      367,  366,  380,  370,  363,    0,  373,  378,  366,  374,
      377,  359,  371,    0,  355,  354,  359,  358,  351,  365,
        0,  355,  353,  355,  348,  356,  351,    0,  344,  344,
      342,    0,  356,  350,  339,  380,  353,  347,    0,  336,
      335,  334,  347,  343,  340,  326,  346,  343,  368,  326,
      323,  324,  336,  335,  319,    0,  333,    0,  324,  322,
      326,    0,  319,    0,    0,  313,    0,  313,  316,    0,
      314,    0,    0,  352,  303,  302,    0,    0,  311,  320,
      304,  318,  306,  301,  311,  314,    0,    0,  299,  299,

      311,    0,  289,  300,  304,    0,  297,  290,  302,  316,
      314,  282,  318,  289,    0,  275,  283,  271,  286,    0,
        0,  275,  283,    0,  267,  306,  280,  265,  619,  619,
      262,  260,  275,  273,  257,  267,    0,  255,    0,  265,
      293,  269,  266,    0,  255,    0,  266,  259,  252,    0,
      251,  256,  263,  619,  254,  247,  247,  246,  240,  238,
      238,  242,  250,  619,  245,  248,  242,  231,  230,  210,
      619,  192,  619,  619,  191,  164,  619,  619,  619,  336,
      339,  342,  187,  171,  345
    } ;

static yyconst flex_int16_t yy_def[486] =
    {   0,
      479,    1,    1,    1,    1,    1,  480,  480,  479,  479,
      479,  479,  479,  479,  479,  481,  479,  479,  482,  479,
      479,  479,  479,  479,  479,  479,  479,  479,  483,  483,
      483,  483,  483,  483,  483,  483,  483,  483,  483,  483,
      483,  484,  484,  484,  484,  484,  484,  484,  484,  484,
      484,  484,  484,  484,  484,  484,  484,  479,  479,  479,
      479,  479,  479,  484,  479,  479,  484,  484,  479,  479,
      479,  479,  479,  481,  481,  479,  479,  479,  479,  479,
      479,  485,  479,  479,  479,  479,  479,  479,  479,  479,
      479,  483,  483,  483,  483,  483,  483,  483,  483,  483,

      483,  483,  483,  483,  483,  483,  483,  483,  483,  483,
      483,  483,  483,  484,  484,  484,  484,  484,  484,  484,
      484,  484,  484,  484,  484,  484,  484,  484,  484,  484,
      484,  484,  484,  484,  484,  484,  484,  484,  484,  484,
      484,  484,  484,  479,  479,  479,  479,  479,  479,  479,
      484,  479,  484,  484,  479,  479,  485,  479,  483,  483,
      483,  483,  483,  483,  483,  483,  483,  483,  483,  483,
      483,  483,  483,  483,  483,  483,  483,  483,  483,  483,
      483,  483,  483,  483,  484,  484,  484,  484,  484,  484,
      484,  484,  484,  484,  484,  484,  484,  484,  484,  484,

      484,  484,  484,  484,  484,  484,  484,  484,  484,  484,
      484,  479,  484,  484,  484,  484,  483,  483,  483,  483,
      483,  483,  483,  483,  483,  483,  483,  483,  483,  483,
      483,  483,  483,  483,  483,  483,  483,  483,  479,  483,
      483,  483,  484,  479,  484,  484,  484,  484,  484,  484,
      484,  484,  484,  484,  484,  484,  484,  484,  479,  484,
      479,  484,  484,  484,  484,  484,  484,  484,  484,  484,
      484,  479,  479,  484,  484,  484,  483,  483,  483,  483,
      483,  483,  483,  483,  483,  483,  483,  483,  483,  483,
      483,  483,  483,  483,  483,  483,  479,  483,  484,  484,

      484,  484,  484,  484,  484,  484,  484,  484,  479,  484,
      484,  484,  484,  484,  484,  484,  484,  484,  484,  484,
      479,  479,  484,  484,  484,  483,  483,  483,  483,  483,
      483,  483,  483,  483,  483,  483,  483,  483,  483,  479,
      484,  484,  484,  484,  484,  484,  484,  484,  484,  479,
      484,  484,  484,  484,  484,  484,  484,  484,  484,  479,
      479,  484,  484,  483,  483,  483,  483,  483,  483,  483,
      483,  483,  483,  483,  483,  479,  484,  484,  484,  484,
      479,  484,  484,  479,  484,  484,  484,  484,  484,  484,
      484,  484,  479,  479,  479,  484,  484,  483,  483,  483,

      483,  483,  483,  483,  479,  484,  484,  479,  479,  484,
      484,  484,  484,  484,  484,  479,  479,  479,  484,  483,
      483,  483,  483,  483,  479,  484,  479,  479,  479,  479,
      484,  479,  484,  479,  479,  479,  484,  483,  483,  479,
      484,  479,  479,  484,  479,  484,  479,  479,  479,  483,
      479,  479,  479,  479,  479,  479,  479,  479,  479,  479,
      479,  479,  479,  479,  479,  479,  479,  479,  479,  479,
      479,  479,  479,  479,  479,  479,  479,  479,    0,  479,
      479,  479,  479,  479,  479
    } ;

static yyconst flex_int16_t yy_nxt[685] =
    {   0,
       10,   11,   12,   13,   14,   15,   16,   17,   18,   19,
       20,   21,   17,   22,   23,   24,   25,   26,   27,   28,
       29,   30,   31,   32,   33,   34,   35,   36,   37,   38,
       39,   40,   41,   35,   10,   10,   42,   43,   44,   45,
       46,   47,   43,   43,   48,   43,   43,   49,   50,   43,
       51,   52,   43,   53,   54,   55,   56,   43,   57,   43,
       43,   43,   17,   58,   17,   59,   60,   61,   62,   59,
       60,   61,   62,   59,   60,   61,   62,   59,   60,   61,
       62,   70,   70,   70,   70,  190,   70,   70,   70,   70,
       70,   70,   70,   70,  191,   78,   71,   83,   63,   84,

       64,   71,   63,   79,   64,   71,   63,   85,   87,   88,
       63,  101,   67,   90,   91,  126,   67,   86,   86,   86,
       86,   68,   93,  127,   96,   68,   65,   99,   66,  100,
       65,   97,   66,  105,   65,  107,   66,   94,   65,  108,
       66,   70,   70,   70,   72,  119,  109,  102,  111,  120,
      106,  110,  115,  128,  112,  121,   71,  116,  124,  129,
      117,  125,  130,  132,  135,  122,  203,  137,  136,  123,
      131,  138,  247,  114,  113,  133,  145,  145,  145,  145,
      204,  153,  139,  140,  145,  145,  145,  145,   83,   92,
       84,   71,  145,  145,  145,  145,  177,  248,   85,   71,

      145,  145,  145,  148,  115,  149,  150,   71,  149,  116,
      151,  178,  117,  478,  179,   71,  152,  152,  152,  152,
       70,   70,   70,   70,   86,   86,   86,   86,   70,   70,
       70,   72,  212,  160,  206,   71,  170,  146,  207,  147,
      477,  171,  476,   71,  161,  146,  253,  147,   86,   86,
       86,   86,  172,  146,  254,  147,  145,  145,  145,  145,
      475,  146,  259,  147,  152,  152,  152,  152,  260,  474,
      213,   71,  145,  145,  145,  148,  149,  150,  261,  149,
      152,  152,  152,  152,  262,  473,  472,   71,  471,  470,
      469,  468,  467,  466,  465,  464,  463,  462,  461,  460,

      459,  458,  457,  456,  455,  454,  453,  452,  441,  451,
      450,  449,  448,  447,  446,  445,  444,  146,  443,  147,
      442,  441,  440,  439,  438,  437,  436,  435,  434,  433,
      432,  431,  430,  146,  429,  147,   69,   69,   69,   74,
      428,   74,   77,  427,   77,  157,  426,  157,  425,  424,
      423,  422,  421,  420,  419,  418,  417,  416,  415,  414,
      413,  412,  411,  410,  409,  408,  407,  406,  405,  404,
      403,  402,  401,  400,  399,  398,  397,  396,  395,  394,
      393,  392,  391,  390,  389,  388,  387,  386,  385,  384,
      383,  382,  381,  380,  379,  378,  377,  376,  375,  374,

      373,  372,  371,  370,  369,  368,  367,  366,  365,  364,
      363,  362,  361,  360,  359,  358,  357,  356,  355,  354,
      353,  352,  351,  350,  349,  348,  347,  346,  345,  344,
      343,  342,  341,  340,  339,  338,  337,  336,  335,  334,
      333,  332,  331,  330,  329,  328,  327,  326,  325,  324,
      323,  322,  321,  320,  319,  318,  317,  316,  315,  314,
      313,  312,  311,  310,  309,  308,  307,  306,  305,  304,
      303,  302,  247,  301,  300,  299,  298,  297,  296,  295,
      294,  293,  292,  291,  290,  289,  288,  287,  286,  285,
      284,  283,  282,  281,  280,  279,  278,  277,  276,  275,

      274,  273,  272,  271,  270,  269,  268,  267,  266,  265,
      264,  263,  258,  257,  256,  255,  252,  251,  250,  249,
      246,  245,  244,  243,  242,  241,  240,  239,  238,  237,
      236,  235,  234,  233,  232,  231,  230,  229,  228,  227,
      226,  225,  224,  223,  222,  221,  220,  219,  218,  217,
      158,  216,  215,  214,  211,  210,  209,  208,  205,  202,
      201,  200,  199,  198,  197,  196,  195,  194,  193,  192,
      189,  188,  187,  186,  185,  184,  183,  182,  181,  180,
      176,  175,  174,  173,  169,  168,  167,  166,  165,  164,
      163,  162,  159,  158,  156,  155,   75,   75,  154,  144,

      143,  142,  141,  134,  123,  118,  104,  103,   98,   95,
       89,   82,   81,   80,   76,   75,   73,  479,    9,  479,
      479,  479,  479,  479,  479,  479,  479,  479,  479,  479,
      479,  479,  479,  479,  479,  479,  479,  479,  479,  479,
      479,  479,  479,  479,  479,  479,  479,  479,  479,  479,
      479,  479,  479,  479,  479,  479,  479,  479,  479,  479,
      479,  479,  479,  479,  479,  479,  479,  479,  479,  479,
      479,  479,  479,  479,  479,  479,  479,  479,  479,  479,
      479,  479,  479,  479
    } ;

static yyconst flex_int16_t yy_chk[685] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    3,    3,    3,    3,    4,
        4,    4,    4,    5,    5,    5,    5,    6,    6,    6,
        6,   11,   11,   11,   11,  120,   12,   12,   12,   12,
       13,   13,   13,   13,  120,   20,   11,   24,    3,   24,

        3,   12,    4,   20,    4,   13,    5,   24,   26,   26,
        6,   34,    5,   28,   28,   48,    6,   25,   25,   25,
       25,    5,   29,   48,   31,    6,    3,   33,    3,   33,
        4,   31,    4,   38,    5,   39,    5,   29,    6,   39,
        6,   14,   14,   14,   14,   45,   40,   34,   41,   45,
       38,   40,   42,   49,   41,   45,   14,   42,   47,   49,
       42,   47,   50,   51,   53,   45,  134,   54,   53,   67,
       50,   54,  190,  484,   41,   51,   59,   59,   59,   59,
      134,   67,   54,   54,   60,   60,   60,   60,   84,  483,
       84,   59,   61,   61,   61,   61,  108,  190,   84,   60,

       62,   62,   62,   62,   64,   63,   63,   61,   63,   64,
       64,  108,   64,  476,  108,   62,   65,   65,   65,   65,
       70,   70,   70,   70,   71,   71,   71,   71,   72,   72,
       72,   72,  142,   94,  136,   70,  103,   59,  136,   59,
      475,  103,  472,   72,   94,   60,  195,   60,   86,   86,
       86,   86,  103,   61,  195,   61,  145,  145,  145,  145,
      470,   62,  200,   62,  146,  146,  146,  146,  200,  469,
      142,  145,  148,  148,  148,  148,  149,  149,  201,  149,
      152,  152,  152,  152,  201,  468,  467,  148,  466,  465,
      463,  462,  461,  460,  459,  458,  457,  456,  455,  453,

      452,  451,  449,  448,  447,  445,  443,  442,  441,  440,
      438,  436,  435,  434,  433,  432,  431,  145,  428,  145,
      427,  426,  425,  423,  422,  419,  418,  417,  416,  414,
      413,  412,  411,  148,  410,  148,  480,  480,  480,  481,
      409,  481,  482,  408,  482,  485,  407,  485,  405,  404,
      403,  401,  400,  399,  396,  395,  394,  393,  392,  391,
      390,  389,  386,  385,  384,  381,  379,  378,  376,  373,
      371,  370,  369,  367,  365,  364,  363,  362,  361,  360,
      359,  358,  357,  356,  355,  354,  353,  352,  351,  350,
      348,  347,  346,  345,  344,  343,  341,  340,  339,  337,

      336,  335,  334,  333,  332,  330,  329,  328,  327,  326,
      325,  323,  322,  321,  320,  319,  318,  317,  315,  314,
      313,  312,  311,  309,  307,  306,  305,  304,  303,  302,
      301,  300,  299,  297,  295,  294,  292,  291,  290,  289,
      287,  284,  283,  282,  281,  280,  278,  277,  276,  275,
      274,  273,  272,  270,  269,  268,  267,  266,  265,  264,
      263,  262,  260,  258,  257,  256,  254,  253,  251,  250,
      249,  248,  247,  246,  245,  243,  242,  239,  238,  237,
      236,  234,  233,  232,  230,  229,  228,  227,  226,  225,
      224,  223,  222,  221,  220,  219,  218,  217,  215,  214,

      213,  212,  211,  210,  209,  208,  207,  206,  205,  204,
      203,  202,  199,  198,  197,  196,  194,  193,  192,  191,
      189,  188,  187,  186,  184,  183,  182,  181,  180,  179,
      178,  177,  176,  175,  174,  173,  172,  171,  170,  169,
      168,  167,  166,  165,  164,  163,  162,  161,  160,  159,
      158,  154,  153,  143,  140,  139,  138,  137,  135,  133,
      131,  130,  129,  128,  127,  125,  124,  123,  122,  121,
      119,  118,  117,  116,  115,  113,  112,  111,  110,  109,
      107,  106,  105,  104,  102,  101,  100,   99,   98,   97,
       96,   95,   93,   83,   81,   77,   75,   74,   68,   58,

       57,   56,   55,   52,   46,   44,   37,   36,   32,   30,
       27,   23,   22,   21,   18,   16,   15,    9,  479,  479,
      479,  479,  479,  479,  479,  479,  479,  479,  479,  479,
      479,  479,  479,  479,  479,  479,  479,  479,  479,  479,
      479,  479,  479,  479,  479,  479,  479,  479,  479,  479,
      479,  479,  479,  479,  479,  479,  479,  479,  479,  479,
      479,  479,  479,  479,  479,  479,  479,  479,  479,  479,
      479,  479,  479,  479,  479,  479,  479,  479,  479,  479,
      479,  479,  479,  479
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 1;

static yyconst flex_int16_t yy_rule_linenum[105] =
    {   0,
       48,   50,   51,   52,   53,   54,   55,   56,   57,   59,
       60,   61,   63,   64,   65,   66,   67,   68,   69,   70,
       71,   72,   73,   75,   76,   77,   78,   79,   80,   81,
       82,   83,   85,   94,   99,  101,  102,  103,  105,  106,
      107,  109,  110,  111,  112,  113,  114,  115,  116,  117,
      118,  119,  120,  122,  123,  124,  125,  126,  127,  128,
      130,  131,  132,  133,  134,  135,  136,  137,  138,  139,
      140,  141,  142,  143,  144,  145,  146,  147,  149,  150,
      151,  152,  153,  154,  155,  156,  157,  158,  159,  160,
      161,  163,  164,  170,  171,  172,  173,  178,  179,  180,

      185,  190,  192,  194
    } ;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "IT.l"
/*--------------------------------------------Prolog------------------------------------------------*/
#line 3 "IT.l"
#include "string.h"
#include "stdio.h"
#include "scanner.h"
#include "parser.h" // for token codes, yylval
#include "list.h"

#define TAB_SIZE 8
#define DIM_LENGTH 3
#define DIMENSION_LENGTH 9

/* Global variables
 * ----------------
 * (For shame!) But we need a few to keep track of things that are
 * preserved between calls to yylex or used outside the scanner.
 */
static int curLineNum, curColNum;
List<const char*> savedLines;

static void resetLine();
static void adjustLineAndColumnNo(char *text, char token);
static void DoBeforeEachAction();

#define YY_USER_ACTION DoBeforeEachAction();

/*----------------------------------------Declarations----------------------------------------------*/
/* States
 * ------
 * A little wrinkle on states is the COPY exclusive state which
 * I added to first match each line and copy it ot the list of lines
 * read before re-processing it. This allows us to print the entire
 * line later to provide context on errors.
 */
 


/*---------------------------------------------Rules------------------------------------------------*/
#line 904 "lex.yy.c"

#define INITIAL 0
#define CODE 1
#define PROGRAM 2
#define COPY 3

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
/* %if-c-only */
#include <unistd.h>
/* %endif */
/* %if-c++-only */
/* %endif */
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

/* %if-c-only Reentrant structure and macros (non-C++). */
/* %if-reentrant */
/* %if-c-only */

static int yy_init_globals (void );

/* %endif */
/* %if-reentrant */
/* %endif */
/* %endif End reentrant structures and macros. */

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

int yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* %if-bison-bridge */
/* %endif */

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

/* %not-for-header */

    static void yyunput (int c,char *buf_ptr  );
    
/* %ok-for-header */

/* %endif */

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT
/* %if-c-only Standard (non-C++) definition */
/* %not-for-header */

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif
/* %ok-for-header */

/* %endif */
#endif

/* %if-c-only */

        static int yy_start_stack_ptr = 0;
        static int yy_start_stack_depth = 0;
        static int *yy_start_stack = NULL;
    
    static void yy_push_state (int new_state );
    
    static void yy_pop_state (void );
    
    static int yy_top_state (void );
    
/* %endif */

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* %if-c-only Standard (non-C++) definition */
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
/* %endif */
/* %if-c++-only C++ definition */
/* %endif */
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
/* %% [5.0] fread()/read() definition of YY_INPUT goes here unless we're doing C++ \ */\
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\
/* %if-c++-only C++ definition \ */\
/* %endif */

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
/* %if-c-only */
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
/* %endif */
/* %if-c++-only */
/* %endif */
#endif

/* %if-tables-serialization structures and prototypes */
/* %not-for-header */

/* %ok-for-header */

/* %not-for-header */

/* %tables-yydmap generated elements */
/* %endif */
/* end tables serialization structures and prototypes */

/* %ok-for-header */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1
/* %if-c-only Standard (non-C++) definition */

extern int yylex (void);

#define YY_DECL int yylex (void)
/* %endif */
/* %if-c++-only C++ definition */
/* %endif */
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

/* %% [6.0] YY_RULE_SETUP definition goes here */
#define YY_RULE_SETUP \
	YY_USER_ACTION

/* %not-for-header */

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
/* %% [7.0] user's declarations go here */
#line 46 "IT.l"


#line 1167 "lex.yy.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
/* %if-c-only */
			yyin = stdin;
/* %endif */
/* %if-c++-only */
/* %endif */

		if ( ! yyout )
/* %if-c-only */
			yyout = stdout;
/* %endif */
/* %if-c++-only */
/* %endif */

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
/* %% [8.0] yymore()-related code goes here */
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

/* %% [9.0] code to set up and find next match goes here */
		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 480 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 619 );

yy_find_action:
/* %% [10.0] code to find the action number goes here */
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

/* %% [11.0] code for yylineno update goes here */

do_action:	/* This label is used only to access EOF actions. */

/* %% [12.0] debug code goes here */
		if ( yy_flex_debug )
			{
			if ( yy_act == 0 )
				fprintf( stderr, "--scanner backing up\n" );
			else if ( yy_act < 105 )
				fprintf( stderr, "--accepting rule at line %ld (\"%s\")\n",
				         (long)yy_rule_linenum[yy_act], yytext );
			else if ( yy_act == 105 )
				fprintf( stderr, "--accepting default rule (\"%s\")\n",
				         yytext );
			else if ( yy_act == 106 )
				fprintf( stderr, "--(end of buffer or a NUL)\n" );
			else
				fprintf( stderr, "--EOF (start condition %d)\n", YY_START );
			}

		switch ( yy_act )
	{ /* beginning of action switch */
/* %% [13.0] actions go here */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 48 "IT.l"
{ /* skip to end of line for // comment */ }
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 50 "IT.l"
adjustLineAndColumnNo(yytext, '{'); return '{';
	YY_BREAK
case 3:
/* rule 3 can match eol */
YY_RULE_SETUP
#line 51 "IT.l"
adjustLineAndColumnNo(yytext, '}'); return '}';	
	YY_BREAK
case 4:
/* rule 4 can match eol */
YY_RULE_SETUP
#line 52 "IT.l"
resetLine();
	YY_BREAK
case 5:
/* rule 5 can match eol */
YY_RULE_SETUP
#line 53 "IT.l"
resetLine(); return New_Line;
	YY_BREAK
case 6:
/* rule 6 can match eol */
YY_RULE_SETUP
#line 54 "IT.l"
resetLine();
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 55 "IT.l"
;		
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 56 "IT.l"
curColNum += TAB_SIZE - curColNum % TAB_SIZE + 1;
	YY_BREAK
case 9:
/* rule 9 can match eol */
YY_RULE_SETUP
#line 57 "IT.l"
adjustLineAndColumnNo(yytext, ':'); return ':';				
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 59 "IT.l"
return Execute;
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 60 "IT.l"
return New;
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 61 "IT.l"
return At;
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 63 "IT.l"
return Program;
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 64 "IT.l"
return Tuple;
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 65 "IT.l"
return Task;
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 66 "IT.l"
return Function;
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 67 "IT.l"
return S_Define;
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 68 "IT.l"
return S_Environment;
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 69 "IT.l"
return S_Initialize;
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 70 "IT.l"
return S_Compute;
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 71 "IT.l"
return S_Partition;
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 72 "IT.l"
return S_Arguments;
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 73 "IT.l"
return S_Results;
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 75 "IT.l"
return T_Integer;
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 76 "IT.l"
return T_Character;
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 77 "IT.l"
return T_Real;
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 78 "IT.l"
return T_Boolean;
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 79 "IT.l"
return T_Epoch;
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 80 "IT.l"
return T_Index;
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 81 "IT.l"
return T_Range;
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 82 "IT.l"
return T_Array;
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 83 "IT.l"
return T_List;
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 85 "IT.l"
{
				int length = strlen(yytext);
				char *dimensionality = (char *) malloc(length);
				strncpy(dimensionality, yytext, length - 1);
				dimensionality[length] = '\0';
				yylval.intConstant = atoi(dimensionality);
				free(dimensionality); 
				return Dimensionality;
			}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 94 "IT.l"
{
				char *dimensionNo = yytext + DIMENSION_LENGTH;
				yylval.intConstant = atoi(dimensionNo);
				return Dimension_No;
			}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 99 "IT.l"
yylval.intConstant = 0; return Dimension_No;
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 101 "IT.l"
return Single;
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 102 "IT.l"
return Double;
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 103 "IT.l"
return Format;
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 105 "IT.l"
return Link;
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 106 "IT.l"
return Create;
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 107 "IT.l"
return Link_or_Create;	
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 109 "IT.l"
return O_LTE;
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 110 "IT.l"
return O_GTE;
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 111 "IT.l"
return O_EQ;
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 112 "IT.l"
return O_NE;
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 113 "IT.l"
return O_RSH;
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 114 "IT.l"
return O_LSH;
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 115 "IT.l"
return O_POWER;
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 116 "IT.l"
return O_OR;
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 117 "IT.l"
return O_OR;
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 118 "IT.l"
return O_AND;
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 119 "IT.l"
return O_AND;
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 120 "IT.l"
return O_SB_RANGE;
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 122 "IT.l"
return R_ADD;
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 123 "IT.l"
return R_MULT;
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 124 "IT.l"
return R_MAX;
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 125 "IT.l"
return R_MAX_ENTRY;
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 126 "IT.l"
return R_MIN;
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 127 "IT.l"
return R_MIN_ENTRY;
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 128 "IT.l"
return R_AVG;	
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 130 "IT.l"
return Repeat;
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 131 "IT.l"
return Activate;
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 132 "IT.l"
return Do;
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 133 "IT.l"
return While;
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 134 "IT.l"
return For;
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 135 "IT.l"
return If;
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 136 "IT.l"
return Else;
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 137 "IT.l"
return In;
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 138 "IT.l"
return From;
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 139 "IT.l"
return To;
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 140 "IT.l"
return Step;
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 141 "IT.l"
return Foreach;
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 142 "IT.l"
return Sequence;
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 143 "IT.l"
return Of;
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 144 "IT.l"
return C_Sub_Partition;
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 145 "IT.l"
return Local;
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 146 "IT.l"
return Range;
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 147 "IT.l"
return Index;
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 149 "IT.l"
return Dynamic;
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 150 "IT.l"
return P_Sub_Partition;
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 151 "IT.l"
return Unordered;
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 152 "IT.l"
return Ordered;
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 153 "IT.l"
return Replicated;
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 154 "IT.l"
return Padding;
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 155 "IT.l"
return Relative_To;
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 156 "IT.l"
return Divides;
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 157 "IT.l"
return Sub_Partitions;
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 158 "IT.l"
return Partitions;
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 159 "IT.l"
return Unpartitioned;
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 160 "IT.l"
return Ascends;
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 161 "IT.l"
return Descends;
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 163 "IT.l"
return Space;
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 164 "IT.l"
{	
				char *dimensionality = yytext + DIM_LENGTH;
				yylval.intConstant = atoi(dimensionality);
				return V_Dimension;
			}
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 170 "IT.l"
yylval.booleanConstant = true; return Boolean;
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 171 "IT.l"
yylval.booleanConstant = false; return Boolean;
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 172 "IT.l"
yylval.characterConstant = yytext[1]; return Character;
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 173 "IT.l"
{	
				yylval.stringConstant = (char *) malloc(strlen(yytext) + 1);
                                strcpy(yylval.stringConstant, yytext);		
				return String;
			} 
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 178 "IT.l"
yylval.doubleConstant = atof(yytext); return Real;
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 179 "IT.l"
yylval.intConstant = atoi(yytext); return Integer;
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 180 "IT.l"
{
				yylval.stringConstant = (char *) malloc(strlen(yytext) + 1);
			 	strcpy(yylval.stringConstant, yytext);
                  		return Type_Name;
			}
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 185 "IT.l"
{	
				yylval.stringConstant = (char *) malloc(strlen(yytext) + 1);
			 	strcpy(yylval.stringConstant, yytext);
                  		return Variable_Name;
			}
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 190 "IT.l"
yylval.characterConstant = yytext[0]; return Space_ID;
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 192 "IT.l"
return yytext[0];
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 194 "IT.l"
fprintf(stderr,"Unexpected character %c (%2X)\n",yytext[0],yytext[0]);
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 196 "IT.l"
ECHO;
	YY_BREAK
#line 1840 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(CODE):
case YY_STATE_EOF(PROGRAM):
case YY_STATE_EOF(COPY):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
/* %% [14.0] code to do back-up for compressed tables and set up yy_cp goes here */
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */
/* %ok-for-header */

/* %if-c++-only */
/* %not-for-header */

/* %ok-for-header */

/* %endif */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
/* %if-c-only */
static int yy_get_next_buffer (void)
/* %endif */
/* %if-c++-only */
/* %endif */
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

/* %if-c-only */
/* %not-for-header */

    static yy_state_type yy_get_previous_state (void)
/* %endif */
/* %if-c++-only */
/* %endif */
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
/* %% [15.0] code to get the start state into yy_current_state goes here */
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
/* %% [16.0] code to find the next state goes here */
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 480 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
/* %if-c-only */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
/* %endif */
/* %if-c++-only */
/* %endif */
{
	register int yy_is_jam;
    /* %% [17.0] code to find the next state, and perhaps do backing up, goes here */
	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 480 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 479);

	return yy_is_jam ? 0 : yy_current_state;
}

/* %if-c-only */

    static void yyunput (int c, register char * yy_bp )
/* %endif */
/* %if-c++-only */
/* %endif */
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

/* %% [18.0] update yylineno here */

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}
/* %if-c-only */

/* %endif */

/* %if-c-only */
#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

/* %endif */
/* %if-c++-only */
/* %endif */
{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

/* %% [19.0] update BOL and yylineno */

	return c;
}
/* %if-c-only */
#endif	/* ifndef YY_NO_INPUT */
/* %endif */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
/* %if-c-only */
    void yyrestart  (FILE * input_file )
/* %endif */
/* %if-c++-only */
/* %endif */
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
/* %if-c-only */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
/* %endif */
/* %if-c++-only */
/* %endif */
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

/* %if-c-only */
static void yy_load_buffer_state  (void)
/* %endif */
/* %if-c++-only */
/* %endif */
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
/* %if-c-only */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
/* %endif */
/* %if-c++-only */
/* %endif */
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
/* %if-c-only */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
/* %endif */
/* %if-c++-only */
/* %endif */
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

/* %if-c-only */

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* %endif */

/* %if-c++-only */
/* %endif */

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
/* %if-c-only */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )
/* %endif */
/* %if-c++-only */
/* %endif */

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

/* %if-c-only */

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
/* %endif */
/* %if-c++-only */
/* %endif */
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
/* %if-c-only */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
/* %endif */
/* %if-c++-only */
/* %endif */
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/* %if-c-or-c++ */
/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
/* %if-c-only */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
/* %endif */
/* %if-c++-only */
/* %endif */
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}
/* %endif */

/* %if-c-or-c++ */
/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
/* %if-c-only */
void yypop_buffer_state (void)
/* %endif */
/* %if-c++-only */
/* %endif */
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}
/* %endif */

/* %if-c-or-c++ */
/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
/* %if-c-only */
static void yyensure_buffer_stack (void)
/* %endif */
/* %if-c++-only */
/* %endif */
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}
/* %endif */

/* %if-c-only */
/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}
/* %endif */

/* %if-c-only */
/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}
/* %endif */

/* %if-c-only */
/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}
/* %endif */

/* %if-c-only */
    static void yy_push_state (int  new_state )
/* %endif */
/* %if-c++-only */
/* %endif */
{
    	if ( (yy_start_stack_ptr) >= (yy_start_stack_depth) )
		{
		yy_size_t new_size;

		(yy_start_stack_depth) += YY_START_STACK_INCR;
		new_size = (yy_start_stack_depth) * sizeof( int );

		if ( ! (yy_start_stack) )
			(yy_start_stack) = (int *) yyalloc(new_size  );

		else
			(yy_start_stack) = (int *) yyrealloc((void *) (yy_start_stack),new_size  );

		if ( ! (yy_start_stack) )
			YY_FATAL_ERROR( "out of memory expanding start-condition stack" );
		}

	(yy_start_stack)[(yy_start_stack_ptr)++] = YY_START;

	BEGIN(new_state);
}

/* %if-c-only */
    static void yy_pop_state  (void)
/* %endif */
/* %if-c++-only */
/* %endif */
{
    	if ( --(yy_start_stack_ptr) < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN((yy_start_stack)[(yy_start_stack_ptr)]);
}

/* %if-c-only */
    static int yy_top_state  (void)
/* %endif */
/* %if-c++-only */
/* %endif */
{
    	return (yy_start_stack)[(yy_start_stack_ptr) - 1];
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

/* %if-c-only */
static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}
/* %endif */
/* %if-c++-only */
/* %endif */

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/* %if-c-only */
/* %if-reentrant */
/* %endif */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/* %if-reentrant */
/* %endif */

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

/* %endif */

/* %if-reentrant */
/* %if-bison-bridge */
/* %endif */
/* %endif if-c-only */

/* %if-c-only */
static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

    (yy_start_stack_ptr) = 0;
    (yy_start_stack_depth) = 0;
    (yy_start_stack) =  NULL;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}
/* %endif */

/* %if-c-only SNIP! this currently causes conflicts with the c++ scanner */
/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Destroy the start condition stack. */
        yyfree((yy_start_stack)  );
        (yy_start_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

/* %if-reentrant */
/* %endif */
    return 0;
}
/* %endif */

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

/* %if-tables-serialization definitions */
/* %define-yytables   The name for this specific scanner's tables. */
#define YYTABLES_NAME "yytables"
/* %endif */

/* %ok-for-header */

#line 196 "IT.l"



/*-------------------------------------------Epilogue----------------------------------------------*/

/* Function: InitScanner
 * ---------------------
 * This function will be called before any calls to yylex().  It is designed
 * to give you an opportunity to do anything that must be done to initialize
 * the scanner (set global variables, configure starting state, etc.). One
 * thing it already does for you is assign the value of the global variable
 * yy_flex_debug that controls whether flex prints debugging information
 * about each token and what rule was matched. If set to false, no information
 * is printed. Setting it to true will give you a running trail that might
 * be helpful when debugging your scanner.
 */
void InitScanner() {
    PrintDebug("lex", "Initializing scanner");
    yy_flex_debug = false;
  //  yy_push_state(COPY); // copy first line at start
    curLineNum = 1;
    curColNum = 1;
}

/* Function: DoBeforeEachAction()
 * ------------------------------
 * This function is installed as the YY_USER_ACTION. This is a place
 * to group code common to all actions.
 * On each match, we fill in the fields to record its location and
 * update our column counter.
 */
static void DoBeforeEachAction() {
   	yylloc.first_line = curLineNum;
   	yylloc.first_column = curColNum;
   	yylloc.last_column = curColNum + yyleng - 1;
   	curColNum += yyleng;
}

/* Function: GetLineNumbered()
 * ---------------------------
 * Returns string with contents of line numbered n or NULL if the
 * contents of that line are not available.  Our scanner copies
 * each line scanned and appends each to a list so we can later
 * retrieve them to report the context for errors.
 */
const char *GetLineNumbered(int num) {
   if (num <= 0 || num > savedLines.NumElements()) return NULL;
   return savedLines.Nth(num-1);
}

/* Functions: BeginCode() and EndCode()
 * ------------------------------------
 * We use newlines as expression seperators inside the code sections. In
 * rest of the source newlines are not important. This two functions are
 * provided so that the parser can set and reset the CODE state so that the
 * lexar recognizes newlines only when required.
 */
void BeginCode() {BEGIN(CODE);}
void EndCode() {BEGIN(INITIAL);} 	
void BeginProgram() {BEGIN(PROGRAM);}
void EndProgram() {BEGIN(INITIAL);} 	

static void resetLine() {
	curColNum = 1; curLineNum++;
}

static void adjustLineAndColumnNo(char *text, char token) {
   	curColNum -= yyleng;
	int length = strlen(text);
	for (int i = 0; i < length; i++) {
		char c = text[i];
		if (c == '\t') {
			curColNum += TAB_SIZE - curColNum % TAB_SIZE + 1;
		} else if (c == '\n') {
			curLineNum++; curColNum = 1;
		} else if (c == token) {
   			yylloc.first_line = curLineNum;
   			yylloc.first_column = curColNum;
   			yylloc.last_column = curColNum;
		}
	}
}

